# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2048']

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: [--line-length=88]
        pass_filenames: false

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.230
    hooks:
      - id: ruff
        args: [--fix, --extend-ignore=E402,E501]

  - repo: https://github.com/kynan/nbstripout.git
    rev: 0.6.0
    hooks:
      - id: nbstripout
